#ifndef VISUAL_SDL_H
# define VISUAL_SDL_H

# include "../include/SDL/begin_code.h"
# include "../include/SDL/close_code.h"
# include "../include/SDL/SDL.h"
# include "../include/SDL/SDL_active.h"
# include "../include/SDL/SDL_audio.h"
# include "../include/SDL/SDL_byteorder.h"
# include "../include/SDL/SDL_cdrom.h"
# include "../include/SDL/SDL_config.h"
# include "../include/SDL/SDL_cpuinfo.h"
# include "../include/SDL/SDL_endian.h"
# include "../include/SDL/SDL_error.h"
# include "../include/SDL/SDL_events.h"
# include "../include/SDL/SDL_getenv.h"
# include "../include/SDL/SDL_joystick.h"
# include "../include/SDL/SDL_keyboard.h"
# include "../include/SDL/SDL_keysym.h"
# include "../include/SDL/SDL_loadso.h"
# include "../include/SDL/SDL_main.h"
# include "../include/SDL/SDL_mouse.h"
# include "../include/SDL/SDL_mutex.h"
# include "../include/SDL/SDL_name.h"
# include "../include/SDL/SDL_opengl.h"
# include "../include/SDL/SDL_platform.h"
# include "../include/SDL/SDL_quit.h"
# include "../include/SDL/SDL_rwops.h"
# include "../include/SDL/SDL_stdinc.h"
# include "../include/SDL/SDL_syswm.h"
# include "../include/SDL/SDL_thread.h"
# include "../include/SDL/SDL_timer.h"
# include "../include/SDL/SDL_types.h"
# include "../include/SDL/SDL_version.h"
# include "../include/SDL/SDL_video.h"

#endif

